-- seed.sql
-- Fixed, reproducible UUIDs for local dev so the API, console, and mobile app can all
-- reference the same demo org/campaign/users without a bootstrap round-trip. Do not reuse
-- these IDs or the placeholder password hash in anything but local development.

INSERT INTO organizations (id, name, legal_entity_name, ein)
VALUES ('00000000-0000-0000-0000-000000000001', 'Demo Field Program', 'Demo Field Program LLC', '00-0000000');

INSERT INTO campaigns (id, org_id, name, type, jurisdiction_state, timezone, start_date, end_date, status)
VALUES (
  '00000000-0000-0000-0000-000000000002',
  '00000000-0000-0000-0000-000000000001',
  'Demo 2026 Canvass', 'candidate', 'CA', 'America/Los_Angeles',
  '2026-09-01', '2026-11-03', 'active'
);

-- password hash below is argon2id for the literal string "devpassword" -- local dev only,
-- generated by apps/api/scripts/hash-dev-password.ts. Real deployments never seed a password.
INSERT INTO users (id, org_id, email, phone, password_hash, status, employment_type)
VALUES
  ('00000000-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000001', 'director@demo.local', '+15550000010', '$argon2id$v=19$m=19456,t=2,p=1$ZGV2c2FsdHNhbHQ$devplaceholderhashonly', 'active', 'w2'),
  ('00000000-0000-0000-0000-000000000011', '00000000-0000-0000-0000-000000000001', 'lead@demo.local',     '+15550000011', '$argon2id$v=19$m=19456,t=2,p=1$ZGV2c2FsdHNhbHQ$devplaceholderhashonly', 'active', 'w2'),
  ('00000000-0000-0000-0000-000000000012', '00000000-0000-0000-0000-000000000001', 'canvasser@demo.local','+15550000012', '$argon2id$v=19$m=19456,t=2,p=1$ZGV2c2FsdHNhbHQ$devplaceholderhashonly', 'active', '1099');

INSERT INTO user_campaign_roles (user_id, campaign_id, role)
VALUES
  ('00000000-0000-0000-0000-000000000010', '00000000-0000-0000-0000-000000000002', 'field_director'),
  ('00000000-0000-0000-0000-000000000011', '00000000-0000-0000-0000-000000000002', 'team_lead'),
  ('00000000-0000-0000-0000-000000000012', '00000000-0000-0000-0000-000000000002', 'canvasser');

INSERT INTO teams (id, campaign_id, name, lead_user_id)
VALUES ('00000000-0000-0000-0000-000000000020', '00000000-0000-0000-0000-000000000002', 'Team Alpha', '00000000-0000-0000-0000-000000000011');

INSERT INTO team_members (team_id, user_id) VALUES
  ('00000000-0000-0000-0000-000000000020', '00000000-0000-0000-0000-000000000011'),
  ('00000000-0000-0000-0000-000000000020', '00000000-0000-0000-0000-000000000012');

INSERT INTO devices (id, user_id, platform, os_version, app_version, attestation_status)
VALUES ('00000000-0000-0000-0000-000000000030', '00000000-0000-0000-0000-000000000012', 'android', '14', '0.1.0', 'passed');

-- California voter-file license so the demo campaign passes the hard block in section 11.1.
INSERT INTO campaign_data_licenses (campaign_id, state, provider, license_reference, executed_at, permitted_uses, verified_by)
VALUES ('00000000-0000-0000-0000-000000000002', 'CA', 'l2', 'DEMO-LICENSE-0001', now(), ARRAY['political_campaign'], '00000000-0000-0000-0000-000000000010');

INSERT INTO consent_records (id, user_id, consent_type, policy_version, policy_text_hash, jurisdiction_state, method)
VALUES
  ('00000000-0000-0000-0000-000000000040', '00000000-0000-0000-0000-000000000012', 'location_tracking', '2026.1', 'sha256:demo', 'CA', 'clickwrap'),
  ('00000000-0000-0000-0000-000000000041', '00000000-0000-0000-0000-000000000012', 'photo_capture',      '2026.1', 'sha256:demo', 'CA', 'clickwrap');

-- A small rectangular demo turf in Sacramento so the map has something to render.
INSERT INTO turfs (id, campaign_id, name, geom, door_count, target_count, est_walk_minutes, est_total_minutes, cut_method, status, created_by)
VALUES (
  '00000000-0000-0000-0000-000000000050',
  '00000000-0000-0000-0000-000000000002',
  'Sun Ray Estates A',
  ST_Multi(ST_GeomFromText(
    'POLYGON((-121.495 38.575, -121.485 38.575, -121.485 38.582, -121.495 38.582, -121.495 38.575))',
    4326
  )),
  120, 84, 95, 180, 'manual', 'published', '00000000-0000-0000-0000-000000000010'
);

INSERT INTO photo_interval_profiles (id, campaign_id, name, created_by)
VALUES ('00000000-0000-0000-0000-000000000060', '00000000-0000-0000-0000-000000000002', 'Default (Beta 5/2, 5-30 doors)', '00000000-0000-0000-0000-000000000010');

INSERT INTO addresses (id, campaign_id, org_id, street_number, street_name, street_type, city, state, zip5, geom)
VALUES (
  '00000000-0000-0000-0000-000000000070',
  '00000000-0000-0000-0000-000000000002',
  '00000000-0000-0000-0000-000000000001',
  '412', 'Oak', 'St', 'Sacramento', 'CA', '95814',
  ST_SetSRID(ST_MakePoint(-121.4901, 38.5785), 4326)
);

INSERT INTO households (id, address_id) VALUES ('00000000-0000-0000-0000-000000000080', '00000000-0000-0000-0000-000000000070');

INSERT INTO voters (id, household_id, address_id, provider, provider_voter_id, first_name, last_name, age, party_registration, vote_history)
VALUES (
  '00000000-0000-0000-0000-000000000090',
  '00000000-0000-0000-0000-000000000080',
  '00000000-0000-0000-0000-000000000070',
  'l2', 'DEMO-L2-0001', 'Maria', 'Gonzalez', 41, 'DEM', '{"2024G":"Y","2022G":"N"}'
);

INSERT INTO walkbooks (id, turf_id, campaign_id, version, door_order)
VALUES (
  '00000000-0000-0000-0000-0000000000a0',
  '00000000-0000-0000-0000-000000000050',
  '00000000-0000-0000-0000-000000000002',
  1, '["00000000-0000-0000-0000-000000000070"]'::jsonb
);

INSERT INTO assignments (id, walkbook_id, campaign_id, user_id, assigned_by, status)
VALUES (
  '00000000-0000-0000-0000-0000000000b0',
  '00000000-0000-0000-0000-0000000000a0',
  '00000000-0000-0000-0000-000000000002',
  '00000000-0000-0000-0000-000000000012',
  '00000000-0000-0000-0000-000000000010',
  'assigned'
);
